version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  EmsApiTestEndpoint: https://emsapibeta.ausdig.com/api
  EmsApiTestUsername:
    secure: IpC7n4Gq5x7QPNSkY4FNrw==
  EmsApiTestPassword:
    secure: qTDOVAxHa2DdMrpU276vMQ==
nuget:
  project_feed: true
before_build:
- ps: '& csharp\EmsApi.Dto\Update-EmsApiSwaggerSpecAuto.ps1'
build:
  project: csharp\EmsApi.sln
  verbosity: minimal
test: off
artifacts:
- path: csharp\bin\*.nupkg
- path: csharp\bin\*.dll
- path: csharp\bin\*.cs